frameworkVersion: "3"

service: cloudfrontLogs
useDotenv: true

provider:
  name: aws
  runtime: python3.11
  memorySize: 512
  timeout: 900
  environment:
    PYTHONPATH: ./src
    MY_AWS_ACCESS_KEY: ${env:MY_AWS_ACCESS_KEY}
    MY_AWS_SECRET_KEY: ${env:MY_AWS_SECRET_KEY}
  region: us-east-1

package:
  patterns:
    # exclude everything
    - "!./**"
    # include only what's needed
    - src/helpers/**
    - src/lambda_handler.py
    - src/providers/**

functions:
  cloudfrontLogs:
    handler: src/lambda_handler.handler
    events:
      - s3:
          bucket: atib-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: logs/
            - suffix: .gz
          existing: true
          forceDeploy: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    fileName: requirements-lambda.txt
