frameworkVersion: "3"

service: cloudfront-logs-parser-lambda-opensearch
useDotenv: true

provider:
  name: aws
  runtime: python3.11
  environment:
    PYTHONPATH: ./src
    MY_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
    MY_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
    OPENSEARCH_HOST: ${{ secrets.OPENSEARCH_HOST }}
    OPENSEARCH_USERNAME: ${{ secrets.OPENSEARCH_USERNAME }}
    OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
  region: ap-south-1
  iam:
    role:
      name: cloudfront-logs-role 

package:
  patterns:
    # exclude everything
    - "!./**"
    # include only what's needed
    - src/cloudfront_parser.py
    - src/lambda_handler.py
    - src/version.py

functions:
  cloudfrontLogs:
    handler: src/lambda_handler.handler
    events:
      - s3:
          bucket: parveztest
          event: s3:ObjectCreated:*
          rules:
            - prefix: /test/
              suffix: .gz
          existing: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    fileName: requirements-lambda.txt
