name: Deploy Lambda

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Run python unit tests
        run: |
          pip install -r requirements.txt
          pytest

      - name: Set up AWS configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region: us-west-2

      - name: Install dependencies
        run: npm ci

      - name: Deploy Lambda function
        run: |
          export MY_AWS_ACCESS_KEY=${{ secrets.MY_AWS_ACCESS_KEY }}
          export MY_AWS_SECRET_KEY=${{ secrets.MY_AWS_SECRET_KEY }}
          export OPENSEARCH_HOST=${{ secrets.OPENSEARCH_HOST }}
          export OPENSEARCH_USERNAME=${{ secrets.OPENSEARCH_USERNAME }}
          export OPENSEARCH_PASSWORD=${{ secrets.OPENSEARCH_PASSWORD }}

          npx serverless deploy --stage dev --verbose
          npx serverless info --stage dev
